[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -jar target/ai-document-search-1.0.0.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
