server:
  port: 8080
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

spring:
  application:
    name: ai-document-search
  
management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.example.aidocumentsearch: DEBUG
    dev.langchain4j: DEBUG

